---
# Codacy configuration for AI-Assisted DevOps Framework
# Primary config - optimizes analysis for shell scripts, TypeScript, and documentation

engines:
  # Shell script analysis
  shellcheck:
    enabled: true
    exclude_paths:
      - 'configs/**'
      - 'tests/**'

  # Security analysis
  semgrep:
    enabled: true
    exclude_paths:
      - 'scripts/**'  # npm postinstall paths are safe (package-relative)

  # Documentation analysis
  markdownlint:
    enabled: true
    exclude_paths:
      - 'configs/**'

  # JSON analysis for configuration templates
  jsonlint:
    enabled: true
    exclude_paths:
      - 'configs/**'

  # TypeScript/JavaScript analysis
  eslint:
    enabled: true
    exclude_paths:
      - 'configs/**'
      - 'tests/**'
      - 'scripts/**'  # npm postinstall uses CommonJS for Node.js compatibility

exclude_paths:
  # Exclude generated or third-party files
  - '.git/**'
  - 'tmp/**'
  - 'logs/**'
  - 'node_modules/**'
  - 'repomix-output.xml'

# File extensions to analyze
file_extensions:
  - '.sh'
  - '.md'
  - '.json'
  - '.txt'
  - '.yml'
  - '.yaml'
  - '.ts'
  - '.js'

# Quality settings
coverage:
  enabled: false
