# CodeFactor configuration
# https://support.codefactor.io/i44-how-to-configure-codefactor

exclude_paths:
  - ".agents/scripts/_archive/**"
  - ".agents/scripts/archived/**"
  - ".agents/scripts/supervisor-archived/**"
  - "tests/**"
  - "backups/**"
  - "node_modules/**"
  - "dist/**"
  - "build/**"
