# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Pro Configuration for AI-Assisted DevOps Framework
# https://docs.coderabbit.ai/guides/review-instructions

language: "en-US"
early_access: false

tone_instructions: |
  This is an AI-Assisted DevOps Framework with comprehensive automation tools.
  Focus on shell script quality, security best practices, and DevOps automation patterns.
  Zero Technical Debt achieved - maintain A-grade ratings across all quality tools.

reviews:
  profile: "chill"
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  
  # Auto-approve simple changes
  auto_review:
    enabled: true
    drafts: false
    
  # Request changes for critical issues
  request_changes_workflow: true
  
  # Exclude certain files from review
  path_filters:
    - "!.agents/tmp/*"
    - "!.agents/memory/*"
    - "!*.log"
    - "!*.tmp"
  
  # Path-specific instructions
  path_instructions:
    - path: "providers/*.sh"
      instructions: |
        Provider helper scripts - focus on:
        - Consistent API patterns
        - Proper error handling
        - Security of credential handling
        - Input validation
        
    - path: ".agents/scripts/*.sh"
      instructions: |
        Automation scripts - focus on:
        - Reliability and robustness
        - Clear logging and feedback
        - Proper exit codes
        - Error recovery mechanisms
        
    - path: "templates/*.sh"
      instructions: |
        Template scripts - focus on:
        - Security (prompt injection protection)
        - Flexibility and reusability
        - Clear documentation
        - Safe defaults
        
    - path: "**/*.ts"
      instructions: |
        TypeScript files - focus on:
        - Type safety and proper typing
        - Error handling patterns
        - Clean code principles

chat:
  auto_reply: true
