#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Marcus Quinn
#
# test-pulse-routines-selector.sh — Regression tests for routine selector bugs
# fixed in pulse-routines.sh and routine-schedule-helper.sh:
#
# History:
#   t2160 — cron schedule extraction truncated at first space (fixed Apr 17)
#   t2175 — two false-match bugs (fixed Apr 18):
#   t2423 — Phase C metachar guard + Phase D end-to-end test (this PR)
#   GH#28808 — fenced examples outside canonical ## Routines dispatched
#   GH#28957 — generated dedicated routines repositories rejected as malformed
#
# Bug 1 (t2175) — t-prefix false match: the grep selector
#   '^\s*-\s*\[x\].*repeat:' matched any completed task whose description text
#   contains the literal "repeat:" (e.g. t2160 quotes `repeat:([^[:space:]]+)`).
#   Combined with the unanchored routine-ID regex (r[0-9]+), this caused r-IDs
#   mentioned inside the description (like "r901, r902") to be treated as live
#   routine IDs and their neighbour text passed to the schedule parser.
#   Observed error: ERROR: unrecognised schedule expression '([^[:space:]]+)`'
#
# Bug 2 (t2175) — persistent unsupported: externally supervised services such
#   as r901 and r912 carry repeat:persistent. The schedule parser and the pulse
#   evaluator both rejected this keyword.
#   Observed error: ERROR: unrecognised schedule expression 'persistent'
#
# Fixes verified here:
#   1. Exactly one supported routine registry is extracted before parsing,
#      including the dedicated layout generated by init-routines-helper.sh
#   2. Fenced, commented, indented, and out-of-section examples are ignored
#   3. Anchored routine-ID parsing accepts numeric and descriptive r-prefixed IDs
#   4. persistent short-circuit in pulse-routines.sh evaluator loop
#   5. persistent handling in routine-schedule-helper.sh (cmd_is_due returns 1)
#   6. (t2423) Phase C metachar guard in routine-schedule-helper.sh _parse_expression
#
# Cases:
#   1. t-prefix with repeat: in description → parser finds 0 routines
#   2. r-prefix with repeat:persistent → parser skips; is-due returns non-zero
#      (not due) with no error output
#   3. r-prefix with repeat:cron(*/2 * * * *) → parser accepts; no parse error
#   4. Mixed: t-prefix false-match + cron + persistent → only cron is dispatchable
#   5. (t2423 Phase C) regex metachars directly passed to schedule helper → exit 2
#      with distinct error message, no "unrecognised schedule expression"
#   6. (t2423 Phase D) Full discovery simulation: mixed TODO with t-prefix false-match
#      lines produces zero "unrecognised schedule expression" errors on stderr
#   7. (GH#28808) Only active content inside one canonical section is selected
#   8. (GH#28808) Missing, duplicate, or malformed boundaries fail closed
#   9. (GH#28544) A stale cron-form r901 cannot invoke pulse-wrapper.sh and a
#      later due descriptive-ID routine still executes in the same evaluator pass
#  10. (GH#28957) The production routines scaffold exposes core and user
#      routines while task lookalikes and malformed/mixed shapes fail closed
#  11. (GH#30592) A pulse-enabled local-only routines repository is evaluated

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)" || exit 1
SCHEDULE_HELPER="${SCRIPT_DIR}/../routine-schedule-helper.sh"
PULSE_ROUTINES="${SCRIPT_DIR}/../pulse-routines.sh"
CORE_ROUTINES="${SCRIPT_DIR}/../routines/core-routines.sh"
INIT_ROUTINES="${SCRIPT_DIR}/../init-routines-helper.sh"

unset _PULSE_ROUTINES_LOADED
# shellcheck source=../pulse-routines.sh
source "$PULSE_ROUTINES"

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
NC=$'\033[0m'

PASS=0
FAIL=0
ERRORS=""

pass() {
	local name="${1:-}"
	printf '%s[PASS]%s %s\n' "$GREEN" "$NC" "$name"
	PASS=$((PASS + 1))
	return 0
}

fail() {
	local name="${1:-}"
	local detail="${2:-}"
	printf '%s[FAIL]%s %s\n' "$RED" "$NC" "$name"
	[[ -n "$detail" ]] && printf '       %s\n' "$detail"
	FAIL=$((FAIL + 1))
	ERRORS="${ERRORS}\n  - ${name}: ${detail}"
	return 0
}

# Create a minimal TODO.md in $1 with the given entries.
_make_todo() {
	local dir="$1"
	shift
	{
		printf '# Tasks\n\n## Routines\n\n'
		for entry in "$@"; do
			printf '%s\n' "$entry"
		done
		printf '\n## Ready\n'
	} >"${dir}/TODO.md"
	return 0
}

# Collect dispatchable IDs through the production section extractor and parser.
_collect_routine_ids() {
	local todo_file="$1"
	local section=""
	local line=""
	section=$(_routine_extract_section "$todo_file") || return 1
	while IFS= read -r line; do
		if _routine_parse_line "$line"; then
			printf '%s\n' "$_RPL_ID"
		fi
	done <<<"$section"
	return 0
}

# _test_selector_cases: cases 1-4 — anchored parser correctness (t2175)
_test_selector_cases() {
	local tmpdir="$1"
	local ids=""

	# Case 1: t-prefix task with repeat: in description → 0 selector matches.
	# Mirrors t2160 TODO entry. OLD selector matched; NEW must not.
	_make_todo "$tmpdir" \
		"- [x] t2160 fix: \`repeat:([^[:space:]]+)\` (r901, r902) ref:GH#19465"
	ids=$(_collect_routine_ids "${tmpdir}/TODO.md")
	if [[ -z "$ids" ]]; then
		pass "Case 1: t-prefix false-match prevented by anchored parser"
	else
		fail "Case 1: t-prefix false-match prevented" "unexpected IDs: $ids"
	fi

	# Case 2: r-prefix with repeat:persistent — parser and is-due both skip.
	# Mirrors r901, which is launched by launchd/systemd rather than by Pulse.
	_make_todo "$tmpdir" \
		"- [x] r901 Supervisor pulse repeat:persistent ~1m run:scripts/pulse-wrapper.sh"
	ids=$(_collect_routine_ids "${tmpdir}/TODO.md")
	local is_due_exit is_due_output
	is_due_output=$("$SCHEDULE_HELPER" is-due "persistent" "0" 2>&1)
	is_due_exit=$?
	if [[ -z "$ids" ]] && [[ "$is_due_exit" -ne 0 ]] && [[ "$is_due_output" != *"ERROR"* ]]; then
		pass "Case 2: r-prefix persistent is skipped with no schedule error"
	else
		fail "Case 2: r-prefix persistent is skipped with no schedule error" \
			"ids=$ids is_due_exit=$is_due_exit output='$is_due_output'"
	fi

	# Case 3: r-prefix with cron schedule — parser accepts, no parse error.
	_make_todo "$tmpdir" \
		"- [x] r904 Worker watchdog repeat:cron(*/2 * * * *) ~10s run:scripts/worker-watchdog.sh --check"
	ids=$(_collect_routine_ids "${tmpdir}/TODO.md")
	local cron_output
	cron_output=$("$SCHEDULE_HELPER" is-due "cron(*/2 * * * *)" "0" 2>&1 >/dev/null)
	if [[ "$ids" == "r904" ]] && [[ "$cron_output" != *"ERROR"* ]]; then
		pass "Case 3: r-prefix cron parses; schedule helper produces no error"
	else
		fail "Case 3: r-prefix cron parses; schedule helper produces no error" \
			"ids=$ids cron_stderr='$cron_output'"
	fi

	# Case 4: Mixed TODO — only the non-persistent r-prefix entry dispatches.
	_make_todo "$tmpdir" \
		"- [x] t2160 fix: \`repeat:([^[:space:]]+)\` (r901, r902) ref:GH#19465" \
		"- [x] r904 Worker watchdog repeat:cron(*/2 * * * *) ~10s run:scripts/worker-watchdog.sh --check" \
		"- [x] r901 Supervisor pulse repeat:persistent ~1m run:scripts/pulse-wrapper.sh"
	ids=$(_collect_routine_ids "${tmpdir}/TODO.md")
	if [[ "$ids" == "r904" ]]; then
		pass "Case 4: mixed TODO — only the dispatchable r-prefix routine parses"
	else
		fail "Case 4: mixed TODO — only the dispatchable r-prefix routine parses" "ids=$ids"
	fi
	return 0
}

# _test_metachar_guard: case 5 — Phase C metachar guard (t2423)
_test_metachar_guard() {
	# Verifies that _parse_expression catches regex patterns before the generic
	# "unrecognised schedule expression" fallback. Guard must:
	#   a) exit 2 (distinct from normal parse error exit 1)
	#   b) emit "regex metacharacters" in the error message
	#   c) NOT emit "unrecognised schedule expression"
	local meta_exit meta_stderr
	meta_stderr=$("$SCHEDULE_HELPER" is-due '([^[:space:]]+)`' '0' 2>&1 >/dev/null)
	meta_exit=$?
	if [[ "$meta_exit" -eq 2 ]] && [[ "$meta_stderr" == *"regex metacharacters"* ]] &&
		[[ "$meta_stderr" != *"unrecognised schedule expression"* ]]; then
		pass "Case 5 (t2423 Phase C): metachar guard fires for regex pattern input"
	else
		fail "Case 5 (t2423 Phase C): metachar guard fires for regex pattern input" \
			"exit=$meta_exit stderr='$meta_stderr'"
	fi
	return 0
}

# _test_e2e_discovery: case 6 — Phase D end-to-end simulation (t2423)
_test_e2e_discovery() {
	local tmpdir="$1"
	# Simulates the full pulse-routines discovery path. TODO.md contains:
	#   - t-prefix tasks with repeat: in descriptions (t2175 false-match triggers)
	#   - Two valid r-prefix routines (cron + persistent)
	# All canonical-section lines are sent through the production parser and then
	# routine-schedule-helper.sh is-due. Zero "unrecognised schedule expression"
	# errors must appear on stderr.
	_make_todo "$tmpdir" \
		"- [x] t2160 fix: \`repeat:([^[:space:]]+)\` (r901, r902) ref:GH#19465" \
		"- [x] t2423 guard: routine-schedule-helper.sh regex metachar guard" \
		"- [x] r904 Worker watchdog repeat:cron(*/2 * * * *) ~10s run:scripts/worker-watchdog.sh --check" \
		"- [x] r901 Supervisor pulse repeat:persistent ~1m run:scripts/pulse-wrapper.sh"

	local e2e_errors=0
	local e2e_stderr=""
	local section=""
	local line=""
	local repeat_expr=""
	local _ise_out=""
	section=$(_routine_extract_section "${tmpdir}/TODO.md") || {
		fail "Case 6 (t2423 Phase D): full discovery path — canonical section extracts" "section extraction failed"
		return 0
	}
	while IFS= read -r line; do
		if ! _routine_parse_line "$line"; then
			continue
		fi
		repeat_expr="$_RPL_REPEAT"
		_ise_out=$("$SCHEDULE_HELPER" is-due "$repeat_expr" "0" 2>&1 >/dev/null)
		if [[ "$_ise_out" == *"unrecognised schedule expression"* ]]; then
			e2e_errors=$((e2e_errors + 1))
			e2e_stderr="${e2e_stderr}|${repeat_expr}: ${_ise_out}"
		fi
	done <<<"$section"

	if [[ "$e2e_errors" -eq 0 ]]; then
		pass "Case 6 (t2423 Phase D): full discovery path — zero unrecognised schedule errors"
	else
		fail "Case 6 (t2423 Phase D): full discovery path — zero unrecognised schedule errors" \
			"got $e2e_errors error(s): $e2e_stderr"
	fi
	return 0
}

# _test_canonical_section_boundaries: cases 7-8 — structural Markdown filtering.
_test_canonical_section_boundaries() {
	local tmpdir="$1"
	local fixture="${tmpdir}/canonical-TODO.md"
	local ids=""
	cat >"$fixture" <<'TODOEOF'
# Tasks

```markdown
## Routines
- [x] r-fenced-example Documentation only repeat:daily(@01:00) run:scripts/fake.sh
```

## Routines

<!--
- [x] r-commented-example Documentation only repeat:daily(@02:00) run:scripts/fake.sh
-->
- [x] r-real-routine Live descriptive ID repeat:daily(@03:00) run:scripts/real.sh
    - [x] r-indented-example Markdown code repeat:daily(@04:00) run:scripts/fake.sh

~~~text
- [x] r-second-fence Documentation only repeat:daily(@05:00) run:scripts/fake.sh
~~~

## Ready

- [x] r-outside-example Not a routine repeat:daily(@06:00) run:scripts/fake.sh
TODOEOF

	ids=$(_collect_routine_ids "$fixture")
	if [[ "$ids" == "r-real-routine" ]]; then
		pass "Case 7 (GH#28808): only active canonical-section content is selected"
	else
		fail "Case 7 (GH#28808): only active canonical-section content is selected" "ids=$ids"
	fi

	local repo_ids=""
	repo_ids=$(_collect_routine_ids "$REPO_ROOT/TODO.md")
	if [[ $'\n'"$repo_ids"$'\n' == *$'\nr-gh-audit-scan\n'* ]] &&
		[[ $'\n'"$repo_ids"$'\n' == *$'\nr-pulse-check\n'* ]] &&
		[[ $'\n'"$repo_ids"$'\n' != *$'\nr004\n'* ]]; then
		pass "Case 7b (GH#28808): repository TODO ignores fenced r004 and keeps descriptive IDs"
	else
		fail "Case 7b (GH#28808): repository TODO ignores fenced r004 and keeps descriptive IDs" "ids=$repo_ids"
	fi

	local malformed_count=0 rc=0
	printf '# Tasks\n\n- [x] r-missing Missing heading repeat:daily(@01:00)\n' >"$fixture"
	rc=0; _routine_extract_section "$fixture" >/dev/null || rc=$?
	[[ "$rc" -eq 1 ]] && malformed_count=$((malformed_count + 1))
	printf '## Routines\n\n## Ready\n\n## Routines\n' >"$fixture"
	rc=0; _routine_extract_section "$fixture" >/dev/null || rc=$?
	[[ "$rc" -eq 1 ]] && malformed_count=$((malformed_count + 1))
	printf '```markdown\n## Routines\n- [x] r-fenced Unclosed repeat:daily(@01:00)\n' >"$fixture"
	rc=0; _routine_extract_section "$fixture" >/dev/null || rc=$?
	[[ "$rc" -eq 1 ]] && malformed_count=$((malformed_count + 1))
	printf '## Routines\n<!-- unclosed\n- [x] r-commented Hidden repeat:daily(@01:00)\n' >"$fixture"
	rc=0; _routine_extract_section "$fixture" >/dev/null || rc=$?
	[[ "$rc" -eq 1 ]] && malformed_count=$((malformed_count + 1))
	if [[ "$malformed_count" -eq 4 ]]; then
		pass "Case 8 (GH#28808): misplaced, duplicate, and malformed boundaries fail closed"
	else
		fail "Case 8 (GH#28808): misplaced, duplicate, and malformed boundaries fail closed" \
			"expected 4 rc=1 failures, got $malformed_count"
	fi

	# GH#34169: the default TODO template has no registry; that is "no routines",
	# not a malformed file, and must not produce a per-cycle diagnostic.
	printf '# TODO\n\n## Ready\n\n- [ ] t001 Ordinary task\n\n## Done\n' >"$fixture"
	rc=0; _routine_extract_section "$fixture" >/dev/null || rc=$?
	if [[ "$rc" -eq 2 ]]; then
		pass "Case 8b (GH#34169): absent registry without routine lines returns no-registry"
	else
		fail "Case 8b (GH#34169): absent registry without routine lines returns no-registry" "rc=$rc"
	fi
	return 0
}

# _test_supervisor_self_recursion_guard: case 9 — production evaluator path.
_test_supervisor_self_recursion_guard() {
	local tmpdir="$1"
	local guard_root="${tmpdir}/self-recursion"
	local test_home="${guard_root}/home"
	local repo_dir="${guard_root}/routines-repo"
	local fake_scripts="${test_home}/.aidevops/agents/scripts"
	local schedule_helper="${guard_root}/always-due.sh"
	local self_marker="${guard_root}/self-invoked"
	local downstream_marker="${guard_root}/downstream-invoked"
	local log_file="${guard_root}/pulse.log"
	local repos_json="${guard_root}/repos.json"
	local state_file="${guard_root}/routine-state.json"

	mkdir -p "$fake_scripts" "$repo_dir"
	cat >"${fake_scripts}/pulse-wrapper.sh" <<'SELF_SCRIPT'
#!/usr/bin/env bash
: >"${ROUTINE_SELF_MARKER:?}"
exit 0
SELF_SCRIPT
	cat >"${fake_scripts}/downstream.sh" <<'DOWNSTREAM_SCRIPT'
#!/usr/bin/env bash
: >"${ROUTINE_DOWNSTREAM_MARKER:?}"
exit 0
DOWNSTREAM_SCRIPT
	cat >"$schedule_helper" <<'SCHEDULE_SCRIPT'
#!/usr/bin/env bash
[[ "${1:-}" == "is-due" ]] || exit 2
exit 0
SCHEDULE_SCRIPT
	chmod +x "${fake_scripts}/pulse-wrapper.sh" "${fake_scripts}/downstream.sh" "$schedule_helper"

	_make_todo "$repo_dir" \
		"- [x] r901 Supervisor pulse repeat:cron(*/2 * * * *) ~1m run:scripts/pulse-wrapper.sh" \
		"- [x] r-downstream-monitor Downstream monitor repeat:daily(@07:10) ~1m run:scripts/downstream.sh"
	printf '{"initialized_repos":[{"slug":"example/routines","path":"%s","pulse":true,"local_only":true}]}\n' \
		"$repo_dir" >"$repos_json"

	if (
		export HOME="$test_home"
		export ROUTINE_SELF_MARKER="$self_marker"
		export ROUTINE_DOWNSTREAM_MARKER="$downstream_marker"
		ROUTINE_SCHEDULE_HELPER="$schedule_helper"
		ROUTINE_STATE_FILE="$state_file"
		ROUTINE_LOG_HELPER="${guard_root}/missing-routine-log-helper.sh"
		HEADLESS_RUNTIME_HELPER="${guard_root}/missing-headless-helper.sh"
		REPOS_JSON="$repos_json"
		LOGFILE="$log_file"
		PULSE_DIR="$guard_root"
		unset _PULSE_ROUTINES_LOADED
		# shellcheck source=../pulse-routines.sh
		source "$PULSE_ROUTINES"
		# shellcheck source=../routines/core-routines.sh
		source "$CORE_ROUTINES"
		get_core_routine_entries | grep -q '^r901|x|.*|repeat:persistent|.*|scripts/pulse-wrapper.sh|script$' &&
			evaluate_routines &&
			[[ ! -e "$self_marker" ]] &&
			[[ -e "$downstream_marker" ]] &&
			jq -e '."r-downstream-monitor".last_status == "success" and (.r901 | not)' "$state_file" >/dev/null &&
			grep -q 'routine r901: skipping self-recursive supervisor target scripts/pulse-wrapper.sh (GH#28544)' "$log_file"
	); then
		pass "Case 9/11 (GH#28544/GH#30592): local-only repo executes safe downstream routine"
	else
		fail "Case 9/11 (GH#28544/GH#30592): local-only repo executes safe downstream routine" \
			"self_marker=$([[ -e "$self_marker" ]] && printf present || printf absent) downstream_marker=$([[ -e "$downstream_marker" ]] && printf present || printf absent)"
	fi
	return 0
}

_test_generated_routines_repository_contract() {
	local tmpdir="$1"
	local fixture_dir="${tmpdir}/generated-routines"
	local ids="" generated_line=""
	mkdir -p "$fixture_dir"
	(
		# Source the production generator in isolation because it owns SCRIPT_DIR.
		# shellcheck source=../init-routines-helper.sh
		source "$INIT_ROUTINES"
		DRY_RUN=false
		_write_todo_md "$fixture_dir"
	)
	while IFS= read -r generated_line || [[ -n "$generated_line" ]]; do
		printf '%s\n' "$generated_line"
		if [[ "$generated_line" == "## User Routines" ]]; then
			printf '%s\n' '- [x] r-user-contract User routine repeat:daily(@07:00) run:custom/scripts/user-contract.sh'
		fi
	done <"${fixture_dir}/TODO.md" >"${fixture_dir}/TODO.md.tmp"
	mv "${fixture_dir}/TODO.md.tmp" "${fixture_dir}/TODO.md"
	printf '%s\n' '- [x] r-task-lookalike Not a routine repeat:daily(@08:00) run:scripts/fake.sh' >>"${fixture_dir}/TODO.md"

	ids=$(_collect_routine_ids "${fixture_dir}/TODO.md")
	if [[ $'\n'"$ids"$'\n' == *$'\nr916\n'* ]] &&
		[[ $'\n'"$ids"$'\n' == *$'\nr917\n'* ]] &&
		[[ $'\n'"$ids"$'\n' == *$'\nr918\n'* ]] &&
		grep -Fqx -- '- [x] r918 Observability retention — archive bounded runtime evidence repeat:daily(@03:10) ~2m run:scripts/observability-helper.sh retention-maintenance --apply --max-partitions 20 --max-duration-seconds 120' "${fixture_dir}/TODO.md" &&
		[[ $'\n'"$ids"$'\n' == *$'\nr-user-contract\n'* ]] &&
		[[ $'\n'"$ids"$'\n' != *$'\nr-task-lookalike\n'* ]]; then
		pass "Case 10 (GH#28957): generated repository exposes core and user routines only"
	else
		fail "Case 10 (GH#28957): generated repository exposes core and user routines only" "ids=$ids"
	fi

	cat >>"${fixture_dir}/TODO.md" <<'MIXED_REGISTRY'

## Routines

- [x] r-mixed-registry Must not dispatch repeat:daily(@09:00) run:scripts/fake.sh
MIXED_REGISTRY
	if _routine_extract_section "${fixture_dir}/TODO.md" >/dev/null; then
		fail "Case 10b (GH#28957): mixed routine registry shapes fail closed"
	else
		pass "Case 10b (GH#28957): mixed routine registry shapes fail closed"
	fi

	cat >"${tmpdir}/malformed-dedicated.md" <<'MALFORMED_DEDICATED'
# Routines

## User Routines
- [x] r-out-of-order Must not dispatch repeat:daily(@09:00) run:scripts/fake.sh

## Core Routines (framework-managed)
## Tasks
MALFORMED_DEDICATED
	if _routine_extract_section "${tmpdir}/malformed-dedicated.md" >/dev/null; then
		fail "Case 10c (GH#28957): out-of-order dedicated headings fail closed"
	else
		pass "Case 10c (GH#28957): out-of-order dedicated headings fail closed"
	fi

	cat >"${tmpdir}/pre-root-heading.md" <<'PRE_ROOT_HEADING'
## Unexpected pre-root heading

# Routines
## Core Routines (framework-managed)
- [x] r-pre-root Must not dispatch repeat:daily(@09:00) run:scripts/fake.sh
## User Routines
## Tasks
PRE_ROOT_HEADING
	if _routine_extract_section "${tmpdir}/pre-root-heading.md" >/dev/null; then
		fail "Case 10d (GH#28957): headings before a dedicated root fail closed"
	else
		pass "Case 10d (GH#28957): headings before a dedicated root fail closed"
	fi
	return 0
}

main() {
	local tmpdir
	tmpdir=$(mktemp -d) || {
		printf 'FATAL: mktemp failed\n' >&2
		exit 1
	}
	# shellcheck disable=SC2064
	trap "rm -rf '$tmpdir'" EXIT

	_test_selector_cases "$tmpdir"
	_test_metachar_guard
	_test_e2e_discovery "$tmpdir"
	_test_canonical_section_boundaries "$tmpdir"
	_test_supervisor_self_recursion_guard "$tmpdir"
	_test_generated_routines_repository_contract "$tmpdir"

	# === Summary ===
	printf '\nResults: %d passed, %d failed\n' "$PASS" "$FAIL"
	if [[ "$FAIL" -gt 0 ]]; then
		printf '\nFailed tests:\n'
		printf '%b\n' "$ERRORS"
		return 1
	fi
	return 0
}

main "$@"
