#!/usr/bin/env python3
"""Query, probe, route, and validate aidevops capability readiness."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import sys
from typing import Any

from capability_readiness_probes import assess
from capability_registry_validation import validate

SCRIPT_DIR = Path(__file__).resolve().parent
AGENTS_DIR = SCRIPT_DIR.parent
DEFAULT_REGISTRY = AGENTS_DIR / "configs" / "capability-registry.json"
GITHUB_TARGET_PATTERN = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def capability_for(registry: dict[str, Any], requested: str) -> dict[str, Any] | None:
    key = requested.casefold()
    return next((item for item in registry["capabilities"] if key in {name.casefold() for name in [item["name"], *item.get("aliases", [])]}), None)


def github_live_evidence(target: str, operation: str) -> tuple[dict[str, str], dict[str, str]]:
    if not GITHUB_TARGET_PATTERN.fullmatch(target):
        raise ValueError("GitHub target must be OWNER/REPO")
    try:
        result = subprocess.run(  # nosec B603
            ["gh", "api", f"repos/{target}"],
            capture_output=True,
            check=False,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired):
        return {"reachable": "false", "authorized": "unknown"}, {"target": target, "operation": operation}
    if result.returncode != 0:
        return {"reachable": "false", "authorized": "unknown"}, {"target": target, "operation": operation}
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError:
        return {"reachable": "false", "authorized": "unknown"}, {"target": target, "operation": operation}
    permissions = payload.get("permissions") or {}
    allowed = operation == "read"
    if operation == "write":
        allowed = bool(permissions.get("push") or permissions.get("maintain") or permissions.get("admin"))
    elif operation == "admin":
        allowed = bool(permissions.get("admin"))
    return {"reachable": "true", "authorized": "true" if allowed else "false"}, {"target": target, "operation": operation}


def generate(registry: dict[str, Any], output: Path) -> None:
    lines = ["<!-- Generated by capability-readiness-helper.py; do not edit. -->", "", "# Capability Registry", "", f"Catalogued capabilities: **{len(registry['capabilities'])}**", "", "| Capability | Owner | Runtimes | Mandatory readiness | Fallback |", "|---|---|---|---|---|"]
    lines.extend(f"| `{item['name']}` | {item['owner']} | {', '.join(item['runtimes'])} | {', '.join(item['required'])} | `{item['fallback']}` |" for item in registry["capabilities"])
    if registry.get("views"):
        lines.extend(["", "## View Ownership", "", "| View | Canonical owner | Derived view |", "|---|---|---|"])
        lines.extend(f"| `{view['name']}` | `{view['owner']}` | `{view.get('derived', '—')}` |" for view in registry["views"])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--fixture", type=Path)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("query", "route"):
        child = sub.add_parser(command)
        child.add_argument("capability", nargs="?" if command == "query" else None)
        child.add_argument("--runtime", choices=["opencode", "claude-code"])
        child.add_argument("--target")
        child.add_argument("--operation", choices=["read", "write", "admin"], default="read")
    sub.add_parser("check")
    generator = sub.add_parser("generate")
    generator.add_argument("--output", type=Path, default=AGENTS_DIR / "reference" / "capability-registry.md")
    return parser.parse_args()


def route_output(result: dict[str, Any], evidence_scope: dict[str, str] | None = None) -> tuple[dict[str, Any], int]:
    ready = result["route_ready"]
    payload = {"decision": "route" if ready else "fallback", "capability": result["name"], "owner": result["owner"] if ready else None, "fallback": None if ready else result["fallback"], "reason": None if ready else "mandatory readiness is false or unknown", "coverage_impact": result["missing_required"], "readiness": result["readiness"], "evidence_scope": evidence_scope}
    return payload, 0 if ready else 3


def main() -> int:
    args = parse_args()
    registry = load_json(args.registry)
    if args.command == "check":
        errors = validate(registry, AGENTS_DIR)
        print(json.dumps({"valid": not errors, "errors": errors}, indent=2))
        return int(bool(errors))
    if args.command == "generate":
        generate(registry, args.output)
        return 0
    selected = capability_for(registry, args.capability) if args.capability else None
    if args.capability and not selected:
        print(json.dumps({"error": "unknown_capability", "requested": args.capability}))
        return 2
    runtime = args.runtime or os.environ.get("AIDEVOPS_RUNTIME", "unknown").casefold()
    fixture = load_json(args.fixture) if args.fixture else None
    live_evidence = None
    evidence_scope = None
    if selected and selected["name"] == "github-operations" and args.target:
        try:
            live_evidence, evidence_scope = github_live_evidence(args.target, args.operation)
        except ValueError as error:
            print(json.dumps({"error": "invalid_target", "detail": str(error)}))
            return 2
    capabilities = [selected] if selected else registry["capabilities"]
    results = [assess(item, registry["dimensions"], runtime, fixture, AGENTS_DIR, live_evidence if item["name"] == "github-operations" else None) for item in capabilities]
    payload, status = route_output(results[0], evidence_scope) if args.command == "route" else ({"schema_version": registry["schema_version"], "runtime": runtime, "capabilities": results}, 0)
    print(json.dumps(payload, indent=2))
    return status


if __name__ == "__main__":
    sys.exit(main())
