#!/usr/bin/env python3
"""Query, probe, route, and validate aidevops capability readiness."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from typing import Any

from capability_readiness_probes import assess
from capability_registry_validation import validate

SCRIPT_DIR = Path(__file__).resolve().parent
AGENTS_DIR = SCRIPT_DIR.parent
DEFAULT_REGISTRY = AGENTS_DIR / "configs" / "capability-registry.json"


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def capability_for(registry: dict[str, Any], requested: str) -> dict[str, Any] | None:
    key = requested.casefold()
    return next((item for item in registry["capabilities"] if key in {name.casefold() for name in [item["name"], *item.get("aliases", [])]}), None)


def generate(registry: dict[str, Any], output: Path) -> None:
    lines = ["<!-- Generated by capability-readiness-helper.py; do not edit. -->", "", "# Capability Registry", "", f"Catalogued capabilities: **{len(registry['capabilities'])}**", "", "| Capability | Owner | Runtimes | Mandatory readiness | Fallback |", "|---|---|---|---|---|"]
    lines.extend(f"| `{item['name']}` | {item['owner']} | {', '.join(item['runtimes'])} | {', '.join(item['required'])} | `{item['fallback']}` |" for item in registry["capabilities"])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--fixture", type=Path)
    sub = parser.add_subparsers(dest="command", required=True)
    for command in ("query", "route"):
        child = sub.add_parser(command)
        child.add_argument("capability", nargs="?" if command == "query" else None)
        child.add_argument("--runtime", choices=["opencode", "claude-code"])
    sub.add_parser("check")
    generator = sub.add_parser("generate")
    generator.add_argument("--output", type=Path, default=AGENTS_DIR / "reference" / "capability-registry.md")
    return parser.parse_args()


def route_output(result: dict[str, Any]) -> tuple[dict[str, Any], int]:
    ready = result["route_ready"]
    payload = {"decision": "route" if ready else "fallback", "capability": result["name"], "owner": result["owner"] if ready else None, "fallback": None if ready else result["fallback"], "reason": None if ready else "mandatory readiness is false or unknown", "coverage_impact": result["missing_required"], "readiness": result["readiness"]}
    return payload, 0 if ready else 3


def main() -> int:
    args = parse_args()
    registry = load_json(args.registry)
    if args.command == "check":
        errors = validate(registry, AGENTS_DIR)
        print(json.dumps({"valid": not errors, "errors": errors}, indent=2))
        return int(bool(errors))
    if args.command == "generate":
        generate(registry, args.output)
        return 0
    selected = capability_for(registry, args.capability) if args.capability else None
    if args.capability and not selected:
        print(json.dumps({"error": "unknown_capability", "requested": args.capability}))
        return 2
    runtime = args.runtime or os.environ.get("AIDEVOPS_RUNTIME", "unknown").casefold()
    fixture = load_json(args.fixture) if args.fixture else None
    capabilities = [selected] if selected else registry["capabilities"]
    results = [assess(item, registry["dimensions"], runtime, fixture, AGENTS_DIR) for item in capabilities]
    payload, status = route_output(results[0]) if args.command == "route" else ({"schema_version": registry["schema_version"], "runtime": runtime, "capabilities": results}, 0)
    print(json.dumps(payload, indent=2))
    return status


if __name__ == "__main__":
    sys.exit(main())
