#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Marcus Quinn
#
# update-baselines.sh — regenerate per-file baseline for validate_positional_parameters
#
# The pre-commit hook (pre-commit-hook.sh) uses ratchet gating (t2384): it blocks
# commits only when the positional-parameter violation count INCREASES vs the
# recorded baseline. This script captures the current counts so the baseline
# stays in sync with intentional cleanups.
#
# Usage:
#   .agents/scripts/update-baselines.sh [--dry-run]
#
# Options:
#   --dry-run   Print what would be written without modifying the baseline file.
#
# Output:
#   Overwrites .agents/configs/positional-params-baseline.json with fresh counts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/shared-constants.sh" 2>/dev/null || true

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
	echo "[ERROR] Not inside a git repository." >&2
	exit 1
}

BASELINE_FILE="${REPO_ROOT}/.agents/configs/positional-params-baseline.json"
DRY_RUN=0
TMP_FILE=""

cleanup() {
	[[ -n "$TMP_FILE" ]] && rm -f "$TMP_FILE"
	return 0
}
trap cleanup EXIT

main() {
	local _arg
	for _arg in "$@"; do
		case "$_arg" in
		--dry-run) DRY_RUN=1 ;;
		-h | --help)
			echo "Usage: update-baselines.sh [--dry-run]"
			echo "Regenerates .agents/configs/positional-params-baseline.json"
			return 0
			;;
		*)
			echo "[ERROR] Unknown argument: $_arg" >&2
			return 1
			;;
		esac
	done

	TMP_FILE="$(mktemp)"

	local total_files=0
	local total_violations=0

	# Build JSON body
	{
		echo '{'
		echo '  "version": 1,'
		echo '  "description": "Per-file baseline counts for validate_positional_parameters ratchet gate (t2384). Generated by update-baselines.sh.",'
		echo '  "files": {'
	} >"$TMP_FILE"

	local first=1
	local file count
	while IFS= read -r file; do
		[[ -z "$file" ]] && continue
		[[ ! -f "${REPO_ROOT}/${file}" ]] && continue

		# Same awk logic as validate_positional_parameters in pre-commit-hook.sh
		# shellcheck disable=SC2016
		count=$(awk '
		{
			line = $0
			gsub(/\047[^\047]*\047/, "", line)
			if (line ~ /^[[:space:]]*#/) next
			sub(/[[:space:]]+#.*/, "", line)
			if (line ~ /local[[:space:]].*=.*\$[1-9]/) next
			if (line ~ /\$[1-9][0-9.,\/]/) next
			if (line ~ /\$[1-9][[:space:]]*\|/) next
			if (line ~ /\$[1-9][[:space:]]+(per|mo(nth)?|year|yr|day|week|hr|hour|flat|each|off|fee|plan|tier|user|seat|unit|addon|setup|trial|credit|annual|quarterly|monthly)/) next
			if (line ~ /\$[1-9]/) print NR ": " $0
		}' "${REPO_ROOT}/${file}" 2>/dev/null | wc -l | tr -d ' ')

		if [[ "$count" -gt 0 ]]; then
			if [[ $first -eq 0 ]]; then
				echo ',' >>"$TMP_FILE"
			fi
			printf '    "%s": %s' "$file" "$count" >>"$TMP_FILE"
			first=0
			((total_files++)) || true
			((total_violations += count)) || true
		fi
	done < <(git -C "$REPO_ROOT" ls-files '*.sh' | sort)

	{
		echo ''
		echo '  }'
		echo '}'
	} >>"$TMP_FILE"

	# Validate JSON
	if command -v jq &>/dev/null; then
		if ! jq . "$TMP_FILE" >/dev/null 2>&1; then
			echo "[ERROR] Generated invalid JSON — aborting." >&2
			return 1
		fi
	fi

	if [[ $DRY_RUN -eq 1 ]]; then
		echo "[DRY-RUN] Would write baseline: ${total_files} files, ${total_violations} total violations"
		echo "[DRY-RUN] Target: ${BASELINE_FILE}"
		if command -v jq &>/dev/null; then
			jq . "$TMP_FILE"
		else
			cat "$TMP_FILE"
		fi
		return 0
	fi

	# Write baseline
	if command -v jq &>/dev/null; then
		jq . "$TMP_FILE" >"${BASELINE_FILE}"
	else
		cp "$TMP_FILE" "${BASELINE_FILE}"
	fi

	echo "[OK] Baseline updated: ${total_files} files, ${total_violations} total violations"
	echo "     Written to: ${BASELINE_FILE}"
	return 0
}

main "$@"
