import { GUI_FILE_ROOTS, type GuiFileExplorerData, type GuiStatusData } from "./contracts";

export const statusFixture: GuiStatusData = {
  aidevops_version: "unknown",
  update: {
    running_version: "unknown",
    installed_version: "unknown",
    restart_required: false,
    message: "The GUI app is using the latest installed aidevops version.",
  },
  runtime: {
    host: "local",
    api: "hono",
    read_only: true,
  },
  machine: {
    id: "local",
    label: "Local machine",
    initials: "LM",
    username: "local",
    hostname: "localhost",
    local_ips: ["127.0.0.1"],
    public_ip: null,
  },
  paths: [
    {
      label: "deployed agents",
      path_ref: "~/.aidevops/agents",
      health: "unchecked",
    },
    {
      label: "settings",
      path_ref: "~/.config/aidevops/settings.json",
      health: "unchecked",
    },
  ],
  helper_availability: [
    {
      name: "aidevops status",
      status: "unchecked",
    },
  ],
  navigation: [
    {
      id: "overview",
      label: "Overview",
      description: "Local setup, update, and API health.",
    },
    {
      id: "agents",
      label: "Agents",
      description: "Read-only file explorer for deployed agent files.",
    },
    {
      id: "config",
      label: "Config",
      description: "Read-only file explorer for aidevops config.",
    },
    {
      id: "git",
      label: "Local Repos",
      description: "Read-only local git workspace browser.",
    },
    {
      id: "security",
      label: "Secrets",
      description: "Secret-reference-only trust boundary.",
    },
  ],
  settings: {
    path_ref: "~/.config/aidevops/settings.json",
    health: "unchecked",
    key_count: 0,
    keys: [],
    value_policy: "keys_only_no_values",
  },
  repos: {
    path_ref: "~/.config/aidevops/repos.json",
    health: "unchecked",
    total: 0,
    repos: [],
  },
  local_repos: {
    path_ref: "~/Git",
    health: "unchecked",
    total: 0,
    excluded_worktrees: 0,
    repos: [],
  },
  oauth_pool: {
    path_ref: "~/.aidevops/oauth-pool.json",
    health: "unchecked",
    value_policy: "metadata_only_no_tokens",
    providers: [
      {
        provider: "anthropic",
        configured: false,
        total: 0,
        available: 0,
        active_or_idle: 0,
        rate_limited: 0,
        auth_errors: 0,
        pending_token: false,
        accounts: [],
      },
      {
        provider: "openai",
        configured: false,
        total: 0,
        available: 0,
        active_or_idle: 0,
        rate_limited: 0,
        auth_errors: 0,
        pending_token: false,
        accounts: [],
      },
      {
        provider: "cursor",
        configured: false,
        total: 0,
        available: 0,
        active_or_idle: 0,
        rate_limited: 0,
        auth_errors: 0,
        pending_token: false,
        accounts: [],
      },
      {
        provider: "google",
        configured: false,
        total: 0,
        available: 0,
        active_or_idle: 0,
        rate_limited: 0,
        auth_errors: 0,
        pending_token: false,
        accounts: [],
      },
    ],
  },
  setup_targets: [
    {
      label: "Deployed agents",
      path_ref: "~/.aidevops/agents/VERSION",
      health: "unchecked",
      purpose: "Canonical aidevops agent, workflow, script, and reference bundle.",
      installed_version: "unknown",
      latest_version: "unknown",
      needs_update: false,
    },
  ],
  ai_apps: [
    {
      name: "OpenCode",
      status: "unchecked",
      app_path_ref: "~/Applications/OpenCode AIDevOps.app",
      binary_path_ref: "not found",
      config_path_ref: "~/.config/opencode/opencode.json",
      aidevops_target_path_ref: "~/.config/opencode/AGENTS.md",
      app_version: "unknown",
      aidevops_version: "unknown",
      latest_version: "unknown",
      needs_update: false,
    },
    {
      name: "Claude Code",
      status: "unchecked",
      app_path_ref: "/Applications/Claude.app",
      binary_path_ref: "not found",
      config_path_ref: "~/.config/Claude/claude_desktop_config.json",
      aidevops_target_path_ref: "~/.config/Claude/AGENTS.md",
      app_version: "unknown",
      aidevops_version: "unknown",
      latest_version: "unknown",
      needs_update: false,
    },
  ],
  capabilities: [
    {
      id: "setup-status",
      label: "Setup/status",
      status: "available",
      doc_ref: "docs/gui/helper-api-contract.md:98",
    },
    {
      id: "repos",
      label: "Repository registry",
      status: "placeholder",
      doc_ref: "docs/gui/helper-api-contract.md:103",
    },
    {
      id: "settings",
      label: "Effective settings",
      status: "placeholder",
      doc_ref: "docs/gui/helper-api-contract.md:101",
    },
  ],
  secrets: [
    {
      name: "GITHUB_TOKEN",
      status: "unchecked",
    },
  ],
  placeholders: [
    "Settings, repos, routines, OpenCode sessions, and capabilities will be added as read-only adapters.",
  ],
};

export const fileExplorerFixture: GuiFileExplorerData = {
  root: GUI_FILE_ROOTS[0],
  current_path_ref: "~/.aidevops/agents",
  current_relative_path: "",
  entry_limit: 80,
  entries: [
    {
      name: "workflows",
      kind: "directory",
      path_ref: "~/.aidevops/agents/workflows",
      relative_path: "workflows",
      extension: "",
      preview_allowed: false,
    },
    {
      name: "AGENTS.md",
      kind: "file",
      path_ref: "~/.aidevops/agents/AGENTS.md",
      relative_path: "AGENTS.md",
      extension: ".md",
      preview_allowed: true,
    },
  ],
  selected_preview: {
    path_ref: "~/.aidevops/agents/AGENTS.md",
    relative_path: "AGENTS.md",
    mode: "markdown",
    language: "md",
    content: "# AI DevOps Framework\n\nRead-only local preview.",
    truncated: false,
    reason: "",
  },
};

export const unsafeSecretFixture = {
  secret_name: "GUI_TEST_SECRET",
  secret_value: "SECRET_SENTINEL_DO_NOT_RENDER",
  private_key: "-----BEGIN PRIVATE KEY-----\nfake\n-----END PRIVATE KEY-----",
  bearer: "Bearer fake-token-value",
  cookie: "sessionid=fake-cookie-value",
  credential_path: "/tmp/fake/credentials.json",
};
