#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2025-2026 Marcus Quinn

# =============================================================================
# Preview Proxy Backend: Traefik File Provider
# =============================================================================
# Manages dynamic Traefik v3 file provider configs for per-worktree preview
# subdomains. Each allocation writes a small YAML file that Traefik hot-reloads.
#
# Expects the user's Traefik instance to watch a dynamic config directory.
# Default: ~/.local-dev-proxy/dynamic/
#
# Config in ~/.config/aidevops/preview-proxy.json:
#   {
#     "backend": "traefik-file",
#     "config_dir": "/Users/<user>/.local-dev-proxy/dynamic/",
#     "domain_template": "{branch_slug}.{repo}.local"
#   }
#
# Design: GH#21560
# =============================================================================

# This file is sourced by preview-proxy-helper.sh — no set -euo pipefail here.
# Functions must be named pp_backend_register and pp_backend_deregister.

# Get Traefik dynamic config directory from preview-proxy config.
_traefik_config_dir() {
    local config_dir
    config_dir="$(_pp_config_get '.config_dir' "${HOME}/.local-dev-proxy/dynamic")"
    echo "$config_dir"
    return 0
}

# Generate the Traefik dynamic config filename for a route.
_traefik_route_file() {
    local repo_slug="$1"
    local branch_slug="$2"
    local config_dir
    config_dir="$(_traefik_config_dir)"

    # Sanitize repo slug for filename: owner/repo -> owner-repo
    local safe_repo="${repo_slug//\//-}"
    echo "${config_dir}/aidevops-preview-${safe_repo}-${branch_slug}.yml"
    return 0
}

# Register a route with Traefik file provider.
# Writes a dynamic config YAML that Traefik hot-reloads.
pp_backend_register() {
    local repo_slug="$1"
    local branch_slug="$2"
    local port="$3"

    local config_dir
    config_dir="$(_traefik_config_dir)"

    # Verify config dir exists
    if [[ ! -d "$config_dir" ]]; then
        print_warning "Traefik dynamic config dir not found: $config_dir"
        print_warning "Create it and configure Traefik to watch it. See reference/preview-proxy.md"
        return 1
    fi

    local route_file
    route_file="$(_traefik_route_file "$repo_slug" "$branch_slug")"

    # Build domain from template
    local domain_template
    domain_template="$(_pp_domain_template)"
    local repo_short="${repo_slug##*/}"
    local domain="${domain_template//\{branch_slug\}/$branch_slug}"
    domain="${domain//\{repo\}/$repo_short}"

    # Sanitize identifiers for Traefik (alphanumeric + hyphen only)
    local safe_repo="${repo_slug//\//-}"
    local router_name="aidevops-${safe_repo}-${branch_slug}"
    local service_name="aidevops-${safe_repo}-${branch_slug}"

    # Write Traefik dynamic config
    # Using printf to avoid heredoc issues with shellcheck
    {
        printf '# Auto-generated by aidevops preview-proxy-helper.sh\n'
        printf '# Repo: %s | Branch slug: %s | Port: %s\n' "$repo_slug" "$branch_slug" "$port"
        printf '# Remove this file to deregister the route.\n'
        printf 'http:\n'
        printf '  routers:\n'
        printf '    %s:\n' "$router_name"
        # shellcheck disable=SC2016  # backticks are Traefik syntax, not shell
        printf '      rule: "Host(\`%s\`)"\n' "$domain"
        printf '      service: "%s"\n' "$service_name"
        printf '      entryPoints:\n'
        printf '        - websecure\n'
        printf '      tls: {}\n'
        printf '  services:\n'
        printf '    %s:\n' "$service_name"
        printf '      loadBalancer:\n'
        printf '        servers:\n'
        printf '          - url: "http://127.0.0.1:%s"\n' "$port"
    } > "$route_file"

    log_info "Traefik route registered: ${domain} -> 127.0.0.1:${port} (${route_file})"
    return 0
}

# Deregister a route from Traefik file provider.
# Simply removes the dynamic config file — Traefik hot-unloads it.
pp_backend_deregister() {
    local repo_slug="$1"
    local branch_slug="$2"

    local route_file
    route_file="$(_traefik_route_file "$repo_slug" "$branch_slug")"

    if [[ -f "$route_file" ]]; then
        rm -f "$route_file"
        log_info "Traefik route deregistered: ${route_file}"
    fi
    return 0
}
