/* Local-only UI: all untrusted source strings are assigned through textContent. */
const state = { projectId: null, view: 'onboarding', projects: [], data: {}, offline: false };
const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => {
  const response = await fetch(`/v1${path}`, { headers: { Accept: 'application/json', ...options.headers }, ...options });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(body.error?.message || `Request failed (${response.status})`), { status: response.status, body });
  return body;
};
const text = (value) => String(value ?? 'Unknown');
const node = (tag, value, className) => { const el = document.createElement(tag); if (className) el.className = className; el.textContent = text(value); return el; };
const notice = (message, error = false) => { const el = $('#notice'); el.hidden = !message; el.className = `notice${error ? ' error' : ''}`; el.textContent = message || ''; };
const safeLink = (url, label = 'Open source') => { try { const parsed = new URL(url, location.origin); if (!['http:', 'https:'].includes(parsed.protocol)) return node('span', 'Unavailable', 'meta'); const a = node('a', label); a.href = parsed.href; a.target = '_blank'; a.rel = 'noopener noreferrer'; return a; } catch { return node('span', 'Unavailable', 'meta'); } };
const card = (title, content, wide = false) => { const el = document.createElement('article'); el.className = `card${wide ? ' wide' : ''}`; el.append(node('h2', title)); if (typeof content === 'string') el.append(node('p', content)); else el.append(content); return el; };
function dataRows(value) { const list = Array.isArray(value) ? value : Object.entries(value || {}).map(([key, item]) => ({ key, ...(typeof item === 'object' ? item : { value: item }) })); const ul = document.createElement('ul'); ul.className = 'list'; if (!list.length) return node('p', 'No recorded evidence.', 'meta'); list.forEach(item => { ul.append(node('li', Object.entries(item).filter(([key]) => !/secret|token|credential|cookie|csrf|authorization|password/i.test(key)).map(([key, val]) => `${key}: ${typeof val === 'object' ? JSON.stringify(val) : val}`).join(' · '))); }); return ul; }
async function loadProject() { if (!state.projectId) return; const id = encodeURIComponent(state.projectId); const endpoints = [`projects/${id}`, `projects/${id}/leads?limit=100`, `projects/${id}/seo`, `projects/${id}/insights`, `projects/${id}/activity`, `projects/${id}/usage`]; const names = ['project', 'leads', 'seo', 'insights', 'activity', 'usage']; const results = await Promise.allSettled(endpoints.map(api)); results.forEach((result, index) => { if (result.status === 'fulfilled') state.data[names[index]] = result.value; }); const failures = results.filter(result => result.status === 'rejected'); notice(failures.length ? `${failures.length} view(s) have partial or unavailable data. Existing evidence remains marked as partial.` : ''); render(); }
function renderOnboarding(root) { const project = state.data.project?.project || {}; const grid = document.createElement('div'); grid.className = 'grid'; const profile = document.createElement('div'); profile.append(node('p', 'Editable facts remain local until an owner-authorized save is supported by this session.'), dataRows(project.profile || project)); grid.append(card('Product facts & provenance', profile)); const form = document.createElement('div'); ['URL or snapshot', 'Manual product facts', 'Candidate queries / communities'].forEach(label => { const field = document.createElement('label'); field.textContent = label; const input = document.createElement(label === 'Manual product facts' ? 'textarea' : 'input'); input.placeholder = 'No evidence supplied'; input.disabled = true; field.append(input); form.append(field); }); grid.append(card('Onboarding state', form)); grid.append(card('Scan progress', dataRows(state.data.activity?.jobs || state.data.activity || {}))); root.append(grid); }
async function disposition(lead, value) { try { await api(`/operator/projects/${encodeURIComponent(state.projectId)}/leads/${encodeURIComponent(lead.lead_id)}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ disposition:value, expected_version:lead.version || 1 }) }); await loadProject(); } catch (error) { notice(error.status === 409 ? 'Conflict detected. Data was not overwritten; refresh and review the latest version.' : error.message, true); } }
function renderLeads(root) { const items = state.data.leads?.items || []; const controls = document.createElement('div'); controls.className = 'controls'; const fields = {}; [['disposition','Disposition'],['score','Minimum score'],['community','Community'],['stage','Stage'],['date','Observed date']].forEach(([key, label]) => { const field = document.createElement('label'); field.textContent = label; const input = document.createElement('input'); input.placeholder = label; input.addEventListener('input', () => filter()); field.append(input); controls.append(field); fields[key] = input; }); root.append(controls); const table = document.createElement('table'); table.innerHTML = '<thead><tr><th>Lead evidence</th><th>Score & freshness</th><th>Local workflow</th></tr></thead>'; const body = document.createElement('tbody'); const filter = () => { body.replaceChildren(); items.filter(lead => { const all = JSON.stringify(lead).toLowerCase(); return (!fields.disposition.value || text(lead.disposition).includes(fields.disposition.value.toLowerCase())) && (!fields.score.value || Number(lead.score || 0) >= Number(fields.score.value)) && ['community','stage','date'].every(key => !fields[key].value || all.includes(fields[key].value.toLowerCase())); }).forEach(lead => { const tr = document.createElement('tr'); const evidence = document.createElement('td'); evidence.append(node('strong', lead.title || lead.author || lead.lead_id), node('p', lead.quote || lead.matching_quote || lead.text || 'No captured quote.', 'quote'), safeLink(lead.permalink || lead.url)); const score = document.createElement('td'); score.append(node('span', `${text(lead.score)} score`, 'badge ok'), node('p', `Intent: ${text(lead.intent)} · Fit: ${text(lead.fit)} · Observed: ${text(lead.observed_at || lead.age)} · Rules: ${text(lead.rules_freshness || 'unknown')}`, 'meta')); const actions = document.createElement('td'); const row = document.createElement('div'); row.className = 'actions'; ['saved','hidden','not-fit','reviewed','responded'].forEach(value => { const button = node('button', value); button.addEventListener('click', () => disposition(lead, value)); row.append(button); }); actions.append(row); tr.append(evidence, score, actions); body.append(tr); }); if (!body.children.length) body.append(Object.assign(document.createElement('tr'), { innerHTML:'<td colspan="3">No leads match the local filters.</td>' })); }; filter(); table.append(body); root.append(card('Lead inbox', table, true)); }
function renderEvidence(root, title, data, labels) { const grid = document.createElement('div'); grid.className = 'grid'; labels.forEach(([name, key]) => { grid.append(card(name, dataRows(data?.[key] || data?.[name.toLowerCase()] || {}))); }); if (!labels.length) grid.append(card(title, dataRows(data))); root.append(grid); }
function renderSettings(root) { const grid = document.createElement('div'); grid.className = 'grid'; const run = node('button', 'Manual scan requires owner authority and a configured budget', 'primary'); run.disabled = true; const controls = document.createElement('div'); controls.append(node('p', 'No credentials are displayed or collected in this interface.'), run); grid.append(card('Manual scans', controls)); const alert = document.createElement('div'); alert.append(node('p', 'Alerts and schedules are owner-only. Unsupported or expired sessions leave controls disabled.'), node('button', 'Enable alerts', 'primary')); alert.querySelector('button').disabled = true; grid.append(card('Schedule & alerts', alert)); root.append(grid); }
function render() { const root = $('#view'); root.replaceChildren(); document.querySelectorAll('.nav button').forEach(button => { button.classList.toggle('active', button.dataset.view === state.view); }); if (!state.projectId) { root.append($('#empty').content.cloneNode(true)); return; } if (state.view === 'onboarding') renderOnboarding(root); else if (state.view === 'leads') renderLeads(root); else if (state.view === 'seo') renderEvidence(root, 'Reddit SEO', state.data.seo, [['Queries & positions','queries'],['History & coverage','history']]); else if (state.view === 'insights') renderEvidence(root, 'Insights', state.data.insights, [['Competitor evidence','competitors'],['Pain themes','themes']]); else if (state.view === 'sources') renderEvidence(root, 'Sources', state.data.project?.project, [['Source coverage','sources']]); else if (state.view === 'activity') renderEvidence(root, 'Activity', state.data.activity, []); else if (state.view === 'usage') renderEvidence(root, 'Usage & budget', state.data.usage, []); else renderSettings(root); }
async function init() { document.querySelectorAll('.nav button').forEach(button => { button.addEventListener('click', () => { state.view = button.dataset.view; render(); }); }); try { const health = await api('/health'); $('#connection').textContent = `Local API v${health.api_version} ready`; $('#connection').className = 'status ok'; const result = await api('/projects'); state.projects = result.projects || []; const select = $('#project-select'); state.projects.forEach(project => { const option = new Option(project.name || project.project_id, project.project_id); select.add(option); }); state.projectId = select.value || null; select.addEventListener('change', () => { state.projectId = select.value; state.data = {}; loadProject(); }); await loadProject(); } catch (_error) { $('#connection').textContent = 'Offline or expired session'; $('#connection').className = 'status error'; notice('The local service is unavailable or this session has expired. No cached result is treated as current.', true); render(); } }
init();
